/**
 * Trilhas locais: a evidência de aprendizagem é a saída de código executado com
 * entradas distintas e uma nova situação de transferência. Não há validação
 * por palavras-chave, quantidade de caracteres ou presença de `print`/`cout`.
 * Os exemplos e soluções são material didático público, não gabaritos secretos.
 */
const test = (label, input, expectedOutput) => ({ label, input, expectedOutput });
const predict = (code, choices, correctIndex, explanation) => ({
  prompt: 'Sem executar, qual será a saída deste programa?',
  code,
  choices,
  correctIndex,
  explanation,
});
const cpp = (body, { headers = [], before = '' } = {}) =>
  [...new Set(['iostream', ...headers])].map(header => `#include <${header}>`).join('\n') +
  `\nusing namespace std;\n\n${before ? `${before}\n\n` : ''}int main() {\n${body}\n    return 0;\n}\n`;

function lesson(language, index, content) {
  const transfer = { ...content.transfer, title: content.transfer.title || 'Leve a ideia para outro problema' };
  return {
    ...content,
    language,
    order: index,
    duration: content.duration || 15,
    kind: content.kind || 'lesson',
    module: index <= 4 ? 'Primeiros programas' : index <= 8 ? 'Organizar e repetir' : 'Construir com autonomia',
    fileName: `${content.id}.${language === 'python' ? 'py' : 'cpp'}`,
    sampleInput: content.cases[0].input,
    transfer,
    checkpoints: [
      { type: 'prediction', label: 'Prever e explicar' },
      { type: 'code', label: 'Executar todos os cenários' },
      { type: 'transfer', label: 'Resolver uma variação' },
    ],
    successMessage: 'Seu programa resolveu todos os cenários. Agora aplique a mesma ideia à variação.',
  };
}

const pythonLessons = [
  lesson('python', 1, {
    id: 'mensagem', title: 'Seu primeiro programa', summary: 'Escreva, execute e confira o que aparece no console.',
    concepts: ['instrução', 'texto', 'print', 'ordem de execução'],
    learn: [
      'Um programa é uma sequência de instruções. Python executa cada linha na ordem em que ela foi escrita.',
      'print("Olá!") mostra um texto. As aspas delimitam o texto; elas não aparecem na saída. Cada print inicia uma nova linha.',
      'O console deve conter somente a saída pedida no desafio. Comentários iniciados por # ajudam quem lê o código e não viram mensagens.',
    ],
    prediction: predict('print("Oi")\nprint("Python")', ['Oi Python', 'Oi\nPython', '"Oi"\n"Python"'], 1, 'São duas instruções print: cada uma escreve seu texto e termina a linha.'),
    task: 'Mostre duas linhas, nesta ordem: Olá, OminiSaber! e Vamos programar. Mantenha pontuação e acentos.',
    starterCode: '# Modifique o texto e acrescente a segunda mensagem.\nprint("Olá, mundo!")\n',
    cases: [test('Duas mensagens, na ordem certa', '', 'Olá, OminiSaber!\nVamos programar.\n')],
    hints: ['Você precisa de duas instruções print.', 'Coloque cada mensagem entre aspas.', 'A primeira linha é Olá, OminiSaber!; a segunda é Vamos programar.'],
    commonMistake: 'Aspas abertas precisam ser fechadas. Escrever sem aspas faz Python procurar uma variável.',
    solutionCode: 'print("Olá, OminiSaber!")\nprint("Vamos programar.")\n',
    transfer: { prompt: 'Crie uma placa de boas-vindas com duas linhas: Laboratório aberto e Experimente uma ideia.', starterCode: '# Escreva a placa.\n', cases: [test('Uma nova placa', '', 'Laboratório aberto\nExperimente uma ideia.\n')], solutionCode: 'print("Laboratório aberto")\nprint("Experimente uma ideia.")\n' },
  }),
  lesson('python', 2, {
    id: 'entrada', title: 'O programa conversa com você', summary: 'Leia uma entrada e componha uma resposta para pessoas diferentes.',
    concepts: ['input', 'variável', 'f-string'],
    learn: [
      'input() lê uma linha da entrada. Guarde o que foi lido: nome = input(). O nome da variável ajuda a explicar para que serve o dado.',
      'Uma f-string permite usar o dado no meio da frase: print(f"Oi, {nome}!"). As chaves indicam onde entra o valor da variável.',
      'Use a caixa Entrada do programa para testar nomes diferentes, inclusive nomes com espaços. Evite input("Nome:") neste desafio: o aviso também seria escrito no console.',
    ],
    prediction: { ...predict('nome = "Ana"\nprint(f"Oi, {nome}!")', ['Oi, nome!', 'Oi, Ana!', 'Ana'], 1, 'O valor Ana substitui {nome} na f-string.'), prompt: 'A variável nome contém Ana. O que será mostrado?' },
    task: 'Leia uma linha com o nome e mostre Bem-vindo, NOME! em uma única linha. Não troque um nome com espaços por apenas a primeira palavra.',
    starterCode: 'nome = input()\n# Mostre a saudação usando o nome recebido.\n',
    cases: [test('Nome curto', 'Ana\n', 'Bem-vindo, Ana!\n'), test('Nome com espaço', 'João Silva\n', 'Bem-vindo, João Silva!\n'), test('Nome de uma letra', 'B\n', 'Bem-vindo, B!\n')],
    hints: ['Guarde o retorno de input() em nome.', 'Use uma f-string para colocar a variável na frase.', 'A frase é print(f"Bem-vindo, {nome}!"). Confira o ponto de exclamação.'],
    commonMistake: 'print("Bem-vindo, {nome}!") sem o f mostra as chaves e a palavra nome, não o conteúdo da variável.',
    solutionCode: 'nome = input()\nprint(f"Bem-vindo, {nome}!")\n',
    transfer: { prompt: 'Leia o nome de um projeto e mostre Projeto: NOME. Preserve as palavras e os espaços.', starterCode: 'projeto = input()\n# Monte a etiqueta do projeto.\n', cases: [test('Projeto simples', 'Robô\n', 'Projeto: Robô\n'), test('Projeto com espaços', 'Horta da escola\n', 'Projeto: Horta da escola\n')], solutionCode: 'projeto = input()\nprint(f"Projeto: {projeto}")\n' },
  }),
  lesson('python', 3, {
    id: 'calculo', title: 'Dados viram cálculos', summary: 'Transforme texto em números e calcule um total em centavos.',
    concepts: ['int', 'multiplicação', 'atribuição', 'dinheiro em centavos'],
    learn: [
      'Mesmo quando você digita 7, input() devolve texto. int(input()) transforma a linha em um número inteiro.',
      'O operador * multiplica números. Primeiro leia os dados, depois calcule, por último mostre o resultado.',
      'Vamos trabalhar com centavos inteiros: 250 representa R$ 2,50. Assim o exercício não depende de arredondamento decimal.',
    ],
    prediction: predict('preco = 250\nquantidade = 3\nprint(preco * quantidade)', ['253', '750', '250250250'], 1, 'Os dois valores são inteiros: 250 × 3 = 750.'),
    task: 'Leia o preço em centavos na primeira linha e a quantidade na segunda. Mostre apenas o total em centavos. Os valores são inteiros não negativos.',
    starterCode: 'preco = int(input())\nquantidade = int(input())\n# Calcule o total.\n',
    cases: [test('Três unidades', '250\n3\n', '750\n'), test('Quantidade zero', '999\n0\n', '0\n'), test('Preço de um centavo', '1\n10\n', '10\n'), test('Quantidade maior', '1234\n50\n', '61700\n')],
    hints: ['Use * entre preço e quantidade.', 'Você pode guardar o produto em total.', 'Mostre somente o número: print(total).'],
    commonMistake: 'Texto multiplicado por um inteiro é repetido. Converta o preço para int antes de calcular.',
    solutionCode: 'preco = int(input())\nquantidade = int(input())\ntotal = preco * quantidade\nprint(total)\n',
    transfer: { prompt: 'Leia dias e páginas por dia em duas linhas. Mostre quantas páginas serão lidas no total.', starterCode: 'dias = int(input())\npaginas_por_dia = int(input())\n', cases: [test('Uma semana', '7\n12\n', '84\n'), test('Nenhum dia', '0\n20\n', '0\n'), test('Uma página por dia', '30\n1\n', '30\n')], solutionCode: 'dias = int(input())\npaginas_por_dia = int(input())\nprint(dias * paginas_por_dia)\n' },
  }),
  lesson('python', 4, {
    id: 'cantina', title: 'Projeto 1 · Pedido da cantina', kind: 'project', duration: 25, summary: 'Combine entrada, cálculo e decisão para aceitar um pedido.',
    concepts: ['if', 'else', 'comparação', 'indentação'],
    learn: [
      'if executa um trecho quando a condição é verdadeira; else cuida da alternativa. Os dois terminam com :.',
      'Linhas recuadas pertencem ao mesmo bloco. Use quatro espaços. pedido <= estoque inclui o caso em que o pedido consome exatamente o que há.',
      'No projeto, o estoque, a quantidade pedida e o preço em centavos chegam em três linhas. Todos são inteiros não negativos. Zero unidades é um pedido aceito de valor zero.',
    ],
    prediction: predict('estoque = 3\npedido = 3\nif pedido <= estoque:\n    print("ACEITO")\nelse:\n    print("SEM ESTOQUE")', ['SEM ESTOQUE', 'ACEITO', 'Nada é mostrado'], 1, 'O operador <= aceita a igualdade: há exatamente a quantidade pedida.'),
    task: 'Leia estoque, pedido e preço em centavos, nessa ordem. Se pedido <= estoque, mostre TOTAL seguido de um espaço e do valor. Senão, mostre SEM ESTOQUE.',
    starterCode: 'estoque = int(input())\npedido = int(input())\npreco = int(input())\n# Decida se pode atender e mostre a resposta.\n',
    cases: [test('Pedido disponível', '10\n3\n250\n', 'TOTAL 750\n'), test('Esgota o estoque', '2\n2\n400\n', 'TOTAL 800\n'), test('Estoque insuficiente', '1\n2\n300\n', 'SEM ESTOQUE\n'), test('Pedido zero', '0\n0\n250\n', 'TOTAL 0\n')],
    hints: ['Compare pedido com estoque antes de calcular a mensagem.', 'No bloco if, use print(f"TOTAL {pedido * preco}").', 'Use <=, não <. No else, escreva print("SEM ESTOQUE").'],
    commonMistake: 'Usar < rejeita o pedido que tem exatamente a quantidade em estoque. Confira esse caso de limite.',
    solutionCode: 'estoque = int(input())\npedido = int(input())\npreco = int(input())\nif pedido <= estoque:\n    print(f"TOTAL {pedido * preco}")\nelse:\n    print("SEM ESTOQUE")\n',
    transfer: { title: 'Variação · Reserva de lugares', prompt: 'Leia lugares disponíveis e pessoas em duas linhas. Mostre RESERVA OK se todas couberem; senão, mostre SALA CHEIA. Zero pessoas cabe em zero lugares.', starterCode: 'lugares = int(input())\npessoas = int(input())\n', cases: [test('Há espaço', '30\n12\n', 'RESERVA OK\n'), test('Limite exato', '10\n10\n', 'RESERVA OK\n'), test('Uma pessoa a mais', '10\n11\n', 'SALA CHEIA\n'), test('Grupo vazio', '0\n0\n', 'RESERVA OK\n')], solutionCode: 'lugares = int(input())\npessoas = int(input())\nif pessoas <= lugares:\n    print("RESERVA OK")\nelse:\n    print("SALA CHEIA")\n' },
  }),
  lesson('python', 5, {
    id: 'repeticao', title: 'Repita com um objetivo', summary: 'Acompanhe o valor de um acumulador durante um laço.',
    concepts: ['for', 'range', 'acumulador', 'limite exclusivo'],
    learn: [
      'for numero in range(1, n + 1) repete o bloco com 1, 2, ..., n. O segundo limite de range não é incluído.',
      'Um acumulador guarda o que você já calculou. Comece total = 0 e, em cada repetição, faça total = total + numero.',
      'Com n = 0, nenhuma repetição acontece. O resultado deve continuar sendo zero. Rastreie n = 3 no papel: total começa em 0 e vira 1, 3 e 6.',
    ],
    prediction: predict('total = 0\nfor numero in range(1, 4):\n    total += numero\nprint(total)', ['3', '6', '10'], 1, 'range(1, 4) produz 1, 2 e 3. O acumulador soma esses três valores.'),
    task: 'Leia um inteiro n entre 0 e 1000 e mostre a soma de todos os inteiros de 1 até n, incluindo n.',
    starterCode: 'n = int(input())\ntotal = 0\n# Repita para acumular os valores de 1 até n.\n',
    cases: [test('Três parcelas', '3\n', '6\n'), test('Nenhuma parcela', '0\n', '0\n'), test('Uma parcela', '1\n', '1\n'), test('Limite maior', '1000\n', '500500\n')],
    hints: ['O início do range é 1.', 'O fim do range deve ser n + 1.', 'Dentro do for, some numero a total; depois do for, mostre total uma vez.'],
    commonMistake: 'print dentro do for mostra parciais em vez de um único total. Observe a indentação.',
    solutionCode: 'n = int(input())\ntotal = 0\nfor numero in range(1, n + 1):\n    total += numero\nprint(total)\n',
    transfer: { prompt: 'Leia n entre 0 e 1000. Some apenas os números pares de 1 até n e mostre o total. numero % 2 == 0 identifica um par.', starterCode: 'n = int(input())\ntotal = 0\n# Use um laço e uma condição.\n', cases: [test('Até seis', '6\n', '12\n'), test('Limite ímpar', '5\n', '6\n'), test('Sem pares', '1\n', '0\n'), test('Intervalo vazio', '0\n', '0\n')], solutionCode: 'n = int(input())\ntotal = 0\nfor numero in range(1, n + 1):\n    if numero % 2 == 0:\n        total += numero\nprint(total)\n' },
  }),
  lesson('python', 6, {
    id: 'listas', title: 'Guarde uma coleção de dados', summary: 'Construa uma lista e descubra o total de uma coleção.',
    concepts: ['list', 'append', 'len', 'sum'],
    learn: [
      'Uma lista guarda vários valores na ordem em que foram adicionados. valores = [] cria uma lista vazia; valores.append(7) acrescenta o número 7.',
      'Leia a quantidade n e use range(n) para ler exatamente n linhas. sum(valores) soma os elementos; len(valores) conta quantos existem.',
      'Uma lista vazia tem comprimento zero e soma zero. Não tente usar valores[0] se ela pode estar vazia.',
    ],
    prediction: predict('valores = [2, 5]\nvalores.append(3)\nprint(len(valores))\nprint(sum(valores))', ['2\n7', '3\n10', '3\n253'], 1, 'append adiciona um terceiro elemento. Os valores 2, 5 e 3 somam 10.'),
    task: 'Leia n entre 0 e 100 e depois n quantidades, uma por linha. Guarde-as em uma lista e mostre a soma. As quantidades são inteiros não negativos.',
    starterCode: 'n = int(input())\nquantidades = []\n# Leia n valores e acrescente cada um à lista.\n',
    cases: [test('Três caixas', '3\n2\n5\n3\n', '10\n'), test('Coleção vazia', '0\n', '0\n'), test('Uma caixa vazia', '1\n0\n', '0\n'), test('Valores repetidos', '4\n10\n10\n10\n10\n', '40\n')],
    hints: ['Use for _ in range(n) para ler n linhas.', 'Faça quantidades.append(int(input())) no laço.', 'Depois de ler todas as linhas, use print(sum(quantidades)).'],
    commonMistake: 'Não coloque input() fora do laço quando há n valores. A quantidade n não faz parte da soma.',
    solutionCode: 'n = int(input())\nquantidades = []\nfor _ in range(n):\n    quantidades.append(int(input()))\nprint(sum(quantidades))\n',
    transfer: { prompt: 'Leia n e n números inteiros. Mostre quantos são estritamente maiores que zero. Zero e negativos não entram na contagem.', starterCode: 'n = int(input())\nvalores = []\n# Guarde os dados e conte os positivos.\n', cases: [test('Sinais misturados', '5\n2\n0\n-3\n4\n1\n', '3\n'), test('Lista vazia', '0\n', '0\n'), test('Nenhum positivo', '3\n0\n-1\n-2\n', '0\n')], solutionCode: 'n = int(input())\nvalores = []\nfor _ in range(n):\n    valores.append(int(input()))\npositivos = 0\nfor valor in valores:\n    if valor > 0:\n        positivos += 1\nprint(positivos)\n' },
  }),
  lesson('python', 7, {
    id: 'funcoes', title: 'Dê um nome à sua solução', summary: 'Separe uma tarefa em uma função que devolve um resultado.',
    concepts: ['def', 'parâmetro', 'return', 'chamada'],
    learn: [
      'def dobro(valor): define uma função. O parâmetro valor recebe o dado de cada chamada; return valor * 2 devolve o resultado.',
      'Definir uma função não a executa. Ela trabalha quando você chama dobro(5). A mesma função pode receber números diferentes.',
      'return devolve um valor para outra parte do programa. print mostra uma mensagem. Aqui, a função calcula e o programa principal cuida da saída.',
    ],
    prediction: predict('def dobro(valor):\n    return valor * 2\n\nprint(dobro(3) + dobro(4))', ['7', '14', '6\n8'], 1, 'As chamadas devolvem 6 e 8; o print mostra a soma, 14.'),
    task: 'Crie dobro(valor), que devolve o dobro. Leia dois inteiros em linhas separadas e mostre o dobro de cada um, também em linhas separadas.',
    starterCode: 'def dobro(valor):\n    # Substitua pass pelo retorno do cálculo.\n    pass\n\na = int(input())\nb = int(input())\n# Chame a função para os dois valores.\n',
    cases: [test('Dois positivos', '3\n4\n', '6\n8\n'), test('Zero e negativo', '0\n-7\n', '0\n-14\n'), test('Valores iguais', '5\n5\n', '10\n10\n')],
    hints: ['Substitua pass por return valor * 2.', 'Uma chamada é dobro(a).', 'Mostre print(dobro(a)) e depois print(dobro(b)).'],
    commonMistake: 'Se não houver return, a função devolve None. Mostrar dentro da função e mostrar a chamada de novo pode produzir mensagens extras.',
    solutionCode: 'def dobro(valor):\n    return valor * 2\n\na = int(input())\nb = int(input())\nprint(dobro(a))\nprint(dobro(b))\n',
    transfer: { prompt: 'Crie a função area(base, altura), que devolve a área de um retângulo. Leia base e altura inteiras não negativas e mostre a área.', starterCode: 'def area(base, altura):\n    pass\n\nbase = int(input())\naltura = int(input())\n', cases: [test('Retângulo', '8\n3\n', '24\n'), test('Altura zero', '12\n0\n', '0\n'), test('Quadrado unitário', '1\n1\n', '1\n')], solutionCode: 'def area(base, altura):\n    return base * altura\n\nbase = int(input())\naltura = int(input())\nprint(area(base, altura))\n' },
  }),
  lesson('python', 8, {
    id: 'estufa', title: 'Projeto 2 · Guardião da estufa', kind: 'project', duration: 30, summary: 'Use uma coleção de leituras para tomar uma decisão explicável.',
    concepts: ['função', 'lista', 'contagem', 'comparação estrita'],
    learn: [
      'O sensor entrega n leituras inteiras, uma por linha. Uma leitura acima de 30 indica calor excessivo; exatamente 30 ainda está no limite permitido.',
      'Divida o problema: uma parte lê os dados, uma função conta quantas leituras estão acima do limite e outra parte mostra a mensagem.',
      'Antes de testar, preveja o resultado para [30, 31, 29]. Somente 31 deve ser contado. Uma coleção vazia não gera alerta.',
    ],
    prediction: predict('leituras = [30, 31, 29]\nalertas = 0\nfor valor in leituras:\n    if valor > 30:\n        alertas += 1\nprint(alertas)', ['1', '2', '3'], 0, 'A condição é > 30, portanto só a leitura 31 gera um alerta.'),
    task: 'Leia n entre 0 e 100 e depois n temperaturas inteiras. Crie contar_alertas(leituras). Se houver alguma temperatura > 30, mostre ALERTA seguido da contagem; senão, mostre OK.',
    starterCode: 'def contar_alertas(leituras):\n    # Conte as temperaturas acima de 30.\n    return 0\n\nn = int(input())\nleituras = []\n# Leia os dados, chame a função e escolha a mensagem.\n',
    cases: [test('Temperaturas seguras', '3\n20\n30\n29\n', 'OK\n'), test('Dois alertas', '4\n31\n30\n45\n10\n', 'ALERTA 2\n'), test('Sem leituras', '0\n', 'OK\n'), test('Uma leitura no limite', '1\n30\n', 'OK\n'), test('Uma leitura acima', '1\n31\n', 'ALERTA 1\n')],
    hints: ['Na função, comece uma contagem em zero e percorra leituras.', 'Aumente a contagem só quando valor > 30 e devolva-a no fim.', 'Se o retorno for maior que zero, mostre f"ALERTA {alertas}"; caso contrário, mostre OK.'],
    commonMistake: '>= 30 conta o limite como alerta. Devolver dentro do laço interrompe a contagem na primeira leitura.',
    solutionCode: 'def contar_alertas(leituras):\n    total = 0\n    for valor in leituras:\n        if valor > 30:\n            total += 1\n    return total\n\nn = int(input())\nleituras = []\nfor _ in range(n):\n    leituras.append(int(input()))\nalertas = contar_alertas(leituras)\nif alertas > 0:\n    print(f"ALERTA {alertas}")\nelse:\n    print("OK")\n',
    transfer: { title: 'Variação · Estoque baixo', prompt: 'Leia n e n quantidades não negativas. Conte as quantidades menores que 5. Se houver alguma, mostre REPOR seguido da contagem; senão, mostre ESTOQUE OK.', starterCode: 'def contar_baixos(quantidades):\n    return 0\n\nn = int(input())\n# Complete leitura, função e saída.\n', cases: [test('Duas reposições', '4\n4\n5\n0\n8\n', 'REPOR 2\n'), test('No limite permitido', '2\n5\n10\n', 'ESTOQUE OK\n'), test('Nenhum produto', '0\n', 'ESTOQUE OK\n')], solutionCode: 'def contar_baixos(quantidades):\n    total = 0\n    for valor in quantidades:\n        if valor < 5:\n            total += 1\n    return total\n\nn = int(input())\nquantidades = []\nfor _ in range(n):\n    quantidades.append(int(input()))\nbaixos = contar_baixos(quantidades)\nif baixos > 0:\n    print(f"REPOR {baixos}")\nelse:\n    print("ESTOQUE OK")\n' },
  }),
  lesson('python', 9, {
    id: 'textos', title: 'Entenda comandos escritos', summary: 'Normalize uma entrada para reconhecer o que a pessoa quis dizer.',
    concepts: ['str', 'strip', 'lower', 'elif'],
    learn: [
      'Textos também têm operações. comando.strip() retira espaços das pontas; comando.lower() converte letras para minúsculas.',
      'Combine as operações: input().strip().lower(). Assim LIGAR, Ligar e ligar são tratados como o mesmo comando.',
      'elif testa outra possibilidade quando o if foi falso. else cuida do que não foi reconhecido. Não invente uma ação para um comando desconhecido.',
    ],
    prediction: predict('comando = "  LIGAR  ".strip().lower()\nprint(comando)', ['  LIGAR  ', 'ligar', 'LIGAR'], 1, 'strip remove espaços das pontas e lower transforma LIGAR em ligar.'),
    task: 'Leia uma linha. Ignore espaços nas pontas e diferenças entre maiúsculas e minúsculas. Para ligar, mostre LUZ ACESA; para desligar, mostre LUZ APAGADA; para outro texto, mostre COMANDO INVALIDO.',
    starterCode: 'comando = input().strip().lower()\n# Reconheça ligar, desligar e a alternativa desconhecida.\n',
    cases: [test('Ligar', 'ligar\n', 'LUZ ACESA\n'), test('Maiúsculas e espaços', '  DeSlIgAr  \n', 'LUZ APAGADA\n'), test('Comando desconhecido', 'piscar\n', 'COMANDO INVALIDO\n'), test('Linha vazia', '\n', 'COMANDO INVALIDO\n')],
    hints: ['Compare comando == "ligar" no if.', 'Use elif comando == "desligar" para a segunda ação.', 'No else, escreva COMANDO INVALIDO.'],
    commonMistake: 'Não confunda =, que atribui, com ==, que compara. strip não remove espaços do meio de uma frase.',
    solutionCode: 'comando = input().strip().lower()\nif comando == "ligar":\n    print("LUZ ACESA")\nelif comando == "desligar":\n    print("LUZ APAGADA")\nelse:\n    print("COMANDO INVALIDO")\n',
    transfer: { prompt: 'Leia uma resposta. Após strip e lower, sim deve virar CONFIRMADO, nao deve virar CANCELADO e qualquer outro texto deve virar REPITA. Use nao sem acento como código de entrada.', starterCode: 'resposta = input()\n# Normalize e interprete a resposta.\n', cases: [test('Confirmar com espaços', ' SIM \n', 'CONFIRMADO\n'), test('Cancelar', 'Nao\n', 'CANCELADO\n'), test('Resposta desconhecida', 'talvez\n', 'REPITA\n'), test('Sem resposta', '\n', 'REPITA\n')], solutionCode: 'resposta = input().strip().lower()\nif resposta == "sim":\n    print("CONFIRMADO")\nelif resposta == "nao":\n    print("CANCELADO")\nelse:\n    print("REPITA")\n' },
  }),
  lesson('python', 10, {
    id: 'dicionarios', title: 'Encontre dados pelo nome', summary: 'Relacione cada produto à sua quantidade usando um dicionário.',
    concepts: ['dict', 'chave', 'valor', 'get'],
    learn: [
      'Um dicionário relaciona uma chave a um valor. estoque = {} começa vazio; estoque["arroz"] = 8 guarda a quantidade do arroz.',
      'Cada cadastro chega em duas linhas: nome e quantidade. Os nomes deste exercício são únicos e precisam ser comparados exatamente como foram lidos.',
      'estoque.get(nome, 0) devolve a quantidade cadastrada ou zero quando não encontra a chave. Isso evita falhar ao consultar um produto que não existe.',
    ],
    prediction: predict('estoque = {"arroz": 8, "feijao": 3}\nprint(estoque.get("milho", 0))', ['Erro', '3', '0'], 2, 'milho não está cadastrado; get devolve o valor padrão zero.'),
    task: 'Leia n entre 0 e 100. Leia n pares de linhas (nome do produto, quantidade não negativa). Leia o nome consultado na última linha. Mostre sua quantidade ou zero se não estiver cadastrado.',
    starterCode: 'n = int(input())\nestoque = {}\n# Leia n cadastros. Depois leia e responda à consulta.\n',
    cases: [test('Produto presente', '2\narroz\n8\nfeijao\n3\narroz\n', '8\n'), test('Produto ausente', '1\narroz\n8\nmilho\n', '0\n'), test('Cadastro vazio', '0\nagua\n', '0\n'), test('Nome com espaços', '1\nleite em po\n12\nleite em po\n', '12\n'), test('Quantidade zero', '1\nbanana\n0\nbanana\n', '0\n')],
    hints: ['Em cada repetição, leia nome e quantidade e faça estoque[nome] = quantidade.', 'A consulta é uma nova linha depois de todos os cadastros.', 'Use print(estoque.get(consulta, 0)).'],
    commonMistake: 'estoque[consulta] falha se a chave não existe. Um produto cadastrado com zero também deve retornar zero.',
    solutionCode: 'n = int(input())\nestoque = {}\nfor _ in range(n):\n    nome = input()\n    quantidade = int(input())\n    estoque[nome] = quantidade\nconsulta = input()\nprint(estoque.get(consulta, 0))\n',
    transfer: { prompt: 'Cadastre n apelidos e seus pontos, em duas linhas por pessoa. Consulte um apelido na última linha. Mostre os pontos; se não existir, mostre SEM CADASTRO. Zero pontos é um cadastro válido.', starterCode: 'n = int(input())\npontos = {}\n# Leia os pares e diferencie ausência de zero pontos.\n', cases: [test('Pessoa presente', '2\nLia\n10\nLeo\n0\nLia\n', '10\n'), test('Presente com zero', '1\nLeo\n0\nLeo\n', '0\n'), test('Não cadastrado', '0\nNina\n', 'SEM CADASTRO\n')], solutionCode: 'n = int(input())\npontos = {}\nfor _ in range(n):\n    nome = input()\n    pontos[nome] = int(input())\nconsulta = input()\nif consulta in pontos:\n    print(pontos[consulta])\nelse:\n    print("SEM CADASTRO")\n' },
  }),
  lesson('python', 11, {
    id: 'depuracao', title: 'Investigue um resultado errado', summary: 'Use contraexemplos pequenos para encontrar dois defeitos.',
    concepts: ['depuração', 'estado inicial', 'caso de limite', 'contraexemplo'],
    learn: [
      'Um programa pode executar sem erro e ainda calcular algo errado. Compare o esperado com o observado e escolha uma entrada pequena que exponha a diferença.',
      'O rascunho soma de 1 até n, mas contém dois defeitos: o valor inicial do acumulador e o fim do range. Teste n = 0 e n = 3 para separá-los.',
      'Corrija uma hipótese de cada vez, execute de novo e depois valide todos os cenários. Não ajuste a saída só para decorar o exemplo mostrado.',
    ],
    prediction: predict('total = 1\nfor numero in range(1, 3):\n    total += numero\nprint(total)', ['3', '4', '6'], 1, 'O código atual começa em 1 e acrescenta 1 e 2, chegando a 4. Esse não é o total correto de 1 até 3.'),
    task: 'Conserte os dois defeitos para que o programa leia n entre 0 e 1000 e mostre a soma de 1 até n, inclusive. Verifique o caso n = 0.',
    starterCode: 'n = int(input())\ntotal = 1\nfor numero in range(1, n):\n    total += numero\nprint(total)\n',
    cases: [test('Revela os dois defeitos', '3\n', '6\n'), test('Acumulador vazio', '0\n', '0\n'), test('Apenas o limite', '1\n', '1\n'), test('Soma maior', '10\n', '55\n')],
    hints: ['Qual deve ser o total antes de somar qualquer número?', 'range(1, n) não inclui n.', 'Comece total em zero e use range(1, n + 1).'],
    commonMistake: 'Um defeito pode esconder outro em certas entradas. Corrigir só range ainda deixa o total com um a mais.',
    solutionCode: 'n = int(input())\ntotal = 0\nfor numero in range(1, n + 1):\n    total += numero\nprint(total)\n',
    transfer: { prompt: 'Repare este contador: ele deve ler n e contar os múltiplos de 3 entre 1 e n, incluindo n. n está entre 0 e 1000.', starterCode: 'n = int(input())\nquantidade = 1\nfor numero in range(1, n):\n    if numero % 3 == 0:\n        quantidade += 1\nprint(quantidade)\n', cases: [test('Inclui o limite', '6\n', '2\n'), test('Sem múltiplos', '2\n', '0\n'), test('Faixa vazia', '0\n', '0\n'), test('Limite não múltiplo', '10\n', '3\n')], solutionCode: 'n = int(input())\nquantidade = 0\nfor numero in range(1, n + 1):\n    if numero % 3 == 0:\n        quantidade += 1\nprint(quantidade)\n' },
  }),
  lesson('python', 12, {
    id: 'loja', title: 'Projeto 3 · Orçamento da feira', kind: 'project', duration: 40, summary: 'Monte uma solução com catálogo, consulta, função e total.',
    concepts: ['decomposição', 'dict', 'função', 'acumulador', 'validação'],
    learn: [
      'O catálogo relaciona nomes de produtos a preços em centavos. Leia n e depois n pares (nome, preço), com os nomes em linhas próprias. Os nomes do catálogo são únicos.',
      'Em seguida, leia m e m pedidos (nome, quantidade). Produtos ausentes do catálogo têm custo zero neste orçamento; pedidos repetidos devem ser somados, não substituídos.',
      'Crie custo(precos, nome, quantidade) para calcular um pedido e use um acumulador para o total. Planeje entradas que testem produto ausente, quantidade zero e catálogo vazio.',
    ],
    prediction: predict('precos = {"suco": 250}\ntotal = 0\nfor nome, quantidade in [("suco", 2), ("bolo", 1)]:\n    total += precos.get(nome, 0) * quantidade\nprint(total)', ['500', '750', 'Erro'], 0, 'Os dois sucos custam 500; bolo não está no catálogo e tem custo zero pela regra do projeto.'),
    task: 'Leia n, n pares de nome/preço, m e m pares de nome/quantidade. Cada dado ocupa sua própria linha. Todos os números são inteiros não negativos; n e m são até 100. Mostre TOTAL seguido do orçamento em centavos. Use custo(precos, nome, quantidade) para organizar a solução.',
    starterCode: 'def custo(precos, nome, quantidade):\n    # Retorne o custo do pedido ou zero para produto ausente.\n    return 0\n\nn = int(input())\nprecos = {}\n# Leia o catálogo, depois os pedidos, e calcule o total.\n',
    cases: [test('Feira com dois produtos', '2\nsuco\n250\nbolo\n400\n2\nsuco\n3\nbolo\n2\n', 'TOTAL 1550\n'), test('Produto ausente e quantidade zero', '1\nsuco\n250\n2\nagua\n4\nsuco\n0\n', 'TOTAL 0\n'), test('Catálogo e pedidos vazios', '0\n0\n', 'TOTAL 0\n'), test('Pedidos repetidos', '1\npao\n125\n3\npao\n1\npao\n2\npao\n3\n', 'TOTAL 750\n'), test('Catálogo vazio com pedido', '0\n1\nfruta\n3\n', 'TOTAL 0\n')],
    hints: ['Preencha precos[nome] com o preço de cada cadastro.', 'Depois de ler m, cada repetição lê nome e quantidade e soma custo(precos, nome, quantidade).', 'A função usa precos.get(nome, 0) * quantidade; mostre f"TOTAL {total}" somente no fim.'],
    commonMistake: 'Sobrescrever total com o custo do último pedido perde os pedidos anteriores. O catálogo e a lista de pedidos têm quantidades diferentes.',
    solutionCode: 'def custo(precos, nome, quantidade):\n    return precos.get(nome, 0) * quantidade\n\nn = int(input())\nprecos = {}\nfor _ in range(n):\n    nome = input()\n    precos[nome] = int(input())\nm = int(input())\ntotal = 0\nfor _ in range(m):\n    nome = input()\n    quantidade = int(input())\n    total += custo(precos, nome, quantidade)\nprint(f"TOTAL {total}")\n',
    transfer: { title: 'Variação · Separar pedidos desconhecidos', prompt: 'Use o mesmo formato de catálogo e pedidos. Some apenas os produtos cadastrados e conte quantas linhas de pedido usam produto ausente, mesmo se a quantidade for zero. Mostre TOTAL valor na primeira linha e DESCONHECIDOS contagem na segunda.', starterCode: '# Reaproveite a ideia do catálogo, mas acrescente a contagem.\n', cases: [test('Um pedido desconhecido', '1\npao\n100\n2\npao\n2\nagua\n3\n', 'TOTAL 200\nDESCONHECIDOS 1\n'), test('Nenhum pedido', '0\n0\n', 'TOTAL 0\nDESCONHECIDOS 0\n'), test('Preço zero é cadastrado', '1\nbrinde\n0\n2\nbrinde\n2\nnovo\n0\n', 'TOTAL 0\nDESCONHECIDOS 1\n')], solutionCode: 'n = int(input())\nprecos = {}\nfor _ in range(n):\n    nome = input()\n    precos[nome] = int(input())\nm = int(input())\ntotal = 0\ndesconhecidos = 0\nfor _ in range(m):\n    nome = input()\n    quantidade = int(input())\n    if nome in precos:\n        total += precos[nome] * quantidade\n    else:\n        desconhecidos += 1\nprint(f"TOTAL {total}")\nprint(f"DESCONHECIDOS {desconhecidos}")\n' },
  }),
];

const cppLessons = [
  lesson('cpp', 1, {
    id: 'mensagem', title: 'Seu primeiro programa C++', summary: 'Conheça a estrutura do programa e faça o console responder.',
    concepts: ['main', 'iostream', 'cout', 'compilação'],
    learn: [
      'C++ passa por uma etapa de compilação antes de executar. #include <iostream> disponibiliza a entrada e a saída; main é onde seu programa começa.',
      'cout << "Olá!" escreve um texto. << conecta o texto à saída. Termine a instrução com ; e use "\\n" para mudar de linha.',
      'As chaves delimitam o corpo de main. return 0 indica que o programa terminou normalmente. Você pode manter essa estrutura e editar o que acontece dentro dela.',
    ],
    prediction: predict(cpp('    cout << "Oi\\n";\n    cout << "C++\\n";'), ['Oi C++', 'Oi\nC++', '"Oi"\n"C++"'], 1, 'Cada texto contém \\n, por isso as duas mensagens ocupam linhas diferentes.'),
    task: 'Mostre duas linhas nesta ordem: Olá, OminiSaber! e Vamos programar. Preserve a pontuação e os acentos.',
    starterCode: cpp('    cout << "Olá, mundo!\\n";\n    // Acrescente a segunda mensagem.'),
    cases: [test('Duas linhas', '', 'Olá, OminiSaber!\nVamos programar.\n')],
    hints: ['Troque o texto do primeiro cout.', 'Acrescente outro cout antes de return 0.', 'Termine cada mensagem com \\n e cada instrução com ;.'],
    commonMistake: 'Esquecer o ponto e vírgula ou fechar uma aspa gera um erro de compilação. Confira a linha indicada e a anterior.',
    solutionCode: cpp('    cout << "Olá, OminiSaber!\\n";\n    cout << "Vamos programar.\\n";'),
    transfer: { prompt: 'Crie duas linhas: Laboratório aberto e Experimente uma ideia.', starterCode: cpp('    // Escreva a placa.'), cases: [test('Uma nova placa', '', 'Laboratório aberto\nExperimente uma ideia.\n')], solutionCode: cpp('    cout << "Laboratório aberto\\n";\n    cout << "Experimente uma ideia.\\n";') },
  }),
  lesson('cpp', 2, {
    id: 'entrada', title: 'Leia uma linha de verdade', summary: 'Receba um nome completo e use-o em uma mensagem.',
    concepts: ['string', 'getline', 'variável', 'cin'],
    learn: [
      '#include <string> permite declarar string nome. Uma string armazena texto, inclusive palavras e espaços.',
      'getline(cin, nome) lê a linha inteira. cin >> nome lê só até o primeiro espaço e não serve para preservar um nome completo neste desafio.',
      'cout << "Oi, " << nome << "!\\n" combina uma parte fixa, o dado recebido e a pontuação.',
    ],
    prediction: predict(cpp('    string nome = "Ana Silva";\n    cout << "Oi, " << nome << "!\\n";', { headers: ['string'] }), ['Oi, nome!', 'Oi, Ana Silva!', 'Ana'], 1, 'cout escreve o conteúdo da variável entre as duas partes fixas.'),
    task: 'Leia uma linha com o nome completo e mostre Bem-vindo, NOME! em uma única linha.',
    starterCode: cpp('    string nome;\n    getline(cin, nome);\n    // Mostre a saudação.', { headers: ['string'] }),
    cases: [test('Nome curto', 'Ana\n', 'Bem-vindo, Ana!\n'), test('Nome com espaços', 'João Silva\n', 'Bem-vindo, João Silva!\n'), test('Uma letra', 'B\n', 'Bem-vindo, B!\n')],
    hints: ['Use o conteúdo da variável nome na saída.', 'Separe as partes da mensagem com <<.', 'A instrução termina com << "!\\n";.'],
    commonMistake: 'cin >> nome não lê um nome completo. Use getline para preservar espaços.',
    solutionCode: cpp('    string nome;\n    getline(cin, nome);\n    cout << "Bem-vindo, " << nome << "!\\n";', { headers: ['string'] }),
    transfer: { prompt: 'Leia uma linha com o nome de um projeto e mostre Projeto: NOME.', starterCode: cpp('    string projeto;\n    // Leia a linha e monte a etiqueta.', { headers: ['string'] }), cases: [test('Projeto curto', 'Robô\n', 'Projeto: Robô\n'), test('Projeto composto', 'Horta da escola\n', 'Projeto: Horta da escola\n')], solutionCode: cpp('    string projeto;\n    getline(cin, projeto);\n    cout << "Projeto: " << projeto << "\\n";', { headers: ['string'] }) },
  }),
  lesson('cpp', 3, {
    id: 'calculo', title: 'Tipos que ajudam a calcular', summary: 'Leia inteiros e calcule um total em centavos.',
    concepts: ['int', 'long long', 'cin', 'multiplicação'],
    learn: [
      'C++ pede o tipo de cada variável. int guarda inteiros usuais; long long oferece mais espaço para totais. Neste exercício, use long long para preço, quantidade e total.',
      'cin >> preco >> quantidade lê dois números separados por espaços ou novas linhas. * multiplica os valores.',
      'Dinheiro será representado por centavos inteiros: 250 significa R$ 2,50. A saída pede o inteiro, sem símbolo monetário.',
    ],
    prediction: predict(cpp('    long long preco = 250, quantidade = 3;\n    cout << preco * quantidade << "\\n";'), ['253', '750', '250250250'], 1, 'As variáveis numéricas são multiplicadas: 250 × 3 = 750.'),
    task: 'Leia preço em centavos e quantidade, nessa ordem. Mostre somente o produto. Os números são inteiros não negativos, até 1000000.',
    starterCode: cpp('    long long preco, quantidade;\n    cin >> preco >> quantidade;\n    // Calcule e mostre o total.'),
    cases: [test('Três unidades', '250\n3\n', '750\n'), test('Quantidade zero', '999\n0\n', '0\n'), test('Um centavo', '1\n10\n', '10\n'), test('Total maior que int usual', '1000000\n1000000\n', '1000000000000\n')],
    hints: ['Multiplique preco por quantidade.', 'Guarde o resultado em long long total, se desejar.', 'Use cout << total << "\\n"; sem texto adicional.'],
    commonMistake: 'Um total muito grande pode ultrapassar int. Use long long para os operandos, não apenas para a variável que recebe o resultado.',
    solutionCode: cpp('    long long preco, quantidade;\n    cin >> preco >> quantidade;\n    long long total = preco * quantidade;\n    cout << total << "\\n";'),
    transfer: { prompt: 'Leia dias e páginas por dia, ambos inteiros não negativos até 1000000. Mostre o total de páginas. Use long long.', starterCode: cpp('    long long dias, paginas;\n    // Leia os dois valores e calcule.'), cases: [test('Uma semana', '7\n12\n', '84\n'), test('Nenhum dia', '0\n20\n', '0\n'), test('Total grande', '1000000\n1000000\n', '1000000000000\n')], solutionCode: cpp('    long long dias, paginas;\n    cin >> dias >> paginas;\n    cout << dias * paginas << "\\n";') },
  }),
  lesson('cpp', 4, {
    id: 'cantina', title: 'Projeto 1 · Pedido da cantina', kind: 'project', duration: 25, summary: 'Verifique estoque e calcule um pedido aceito.',
    concepts: ['if', 'else', 'comparação', 'bloco'],
    learn: [
      'if (condicao) executa um bloco quando a condição é verdadeira. else escolhe a alternativa. Use chaves para delimitar cada bloco.',
      'pedido <= estoque inclui a igualdade. Com exatamente a quantidade necessária, o pedido deve ser aceito.',
      'Leia estoque, pedido e preço em centavos. Todos são inteiros não negativos, até 1000000. Zero unidades gera total zero, mesmo se o estoque também for zero.',
    ],
    prediction: predict(cpp('    int estoque = 3, pedido = 3;\n    if (pedido <= estoque) {\n        cout << "ACEITO\\n";\n    } else {\n        cout << "SEM ESTOQUE\\n";\n    }'), ['SEM ESTOQUE', 'ACEITO', 'Nenhuma saída'], 1, '<= inclui a igualdade: três unidades em estoque atendem um pedido de três.'),
    task: 'Leia estoque, pedido e preço. Se pedido <= estoque, mostre TOTAL seguido do valor em centavos. Senão, mostre SEM ESTOQUE. Use long long para os números.',
    starterCode: cpp('    long long estoque, pedido, preco;\n    cin >> estoque >> pedido >> preco;\n    // Decida qual resposta mostrar.'),
    cases: [test('Pedido possível', '10\n3\n250\n', 'TOTAL 750\n'), test('Estoque exato', '2\n2\n400\n', 'TOTAL 800\n'), test('Uma unidade a menos', '1\n2\n300\n', 'SEM ESTOQUE\n'), test('Pedido zero', '0\n0\n250\n', 'TOTAL 0\n'), test('Total grande', '1000000\n1000000\n1000000\n', 'TOTAL 1000000000000\n')],
    hints: ['A condição usa pedido <= estoque.', 'No if, envie "TOTAL " e pedido * preco para cout.', 'No else, mostre "SEM ESTOQUE\\n".'],
    commonMistake: 'Usar = em uma condição faz atribuição. Para este projeto, use a comparação <=.',
    solutionCode: cpp('    long long estoque, pedido, preco;\n    cin >> estoque >> pedido >> preco;\n    if (pedido <= estoque) {\n        cout << "TOTAL " << pedido * preco << "\\n";\n    } else {\n        cout << "SEM ESTOQUE\\n";\n    }'),
    transfer: { title: 'Variação · Reserva de lugares', prompt: 'Leia lugares e pessoas. Mostre RESERVA OK se pessoas <= lugares; senão, SALA CHEIA. São inteiros não negativos.', starterCode: cpp('    int lugares, pessoas;\n    cin >> lugares >> pessoas;\n    // Aplique a nova regra.'), cases: [test('Há espaço', '30\n12\n', 'RESERVA OK\n'), test('Sala no limite', '10\n10\n', 'RESERVA OK\n'), test('Não cabe', '10\n11\n', 'SALA CHEIA\n'), test('Grupo vazio', '0\n0\n', 'RESERVA OK\n')], solutionCode: cpp('    int lugares, pessoas;\n    cin >> lugares >> pessoas;\n    if (pessoas <= lugares) {\n        cout << "RESERVA OK\\n";\n    } else {\n        cout << "SALA CHEIA\\n";\n    }') },
  }),
  lesson('cpp', 5, {
    id: 'repeticao', title: 'Controle uma repetição', summary: 'Veja começo, condição e avanço de um laço for.',
    concepts: ['for', 'incremento', 'acumulador', 'limite'],
    learn: [
      'for (int i = 1; i <= n; i++) define três partes: começar em 1, continuar enquanto i <= n, aumentar i após cada repetição.',
      'Um acumulador começa em zero. total += i acrescenta o valor atual, sem perder a soma anterior.',
      'Se n for zero, a condição falha antes da primeira repetição. O programa deve escrever zero uma vez. Não coloque a saída do total dentro do laço.',
    ],
    prediction: predict(cpp('    int total = 0;\n    for (int i = 1; i <= 3; i++) {\n        total += i;\n    }\n    cout << total << "\\n";'), ['3', '6', '10'], 1, 'O laço acumula 1, 2 e 3, chegando a 6.'),
    task: 'Leia n entre 0 e 1000. Mostre a soma dos inteiros de 1 até n, inclusive.',
    starterCode: cpp('    int n;\n    cin >> n;\n    long long total = 0;\n    // Acrescente o laço e a saída.'),
    cases: [test('Três parcelas', '3\n', '6\n'), test('Intervalo vazio', '0\n', '0\n'), test('Uma parcela', '1\n', '1\n'), test('Limite maior', '1000\n', '500500\n')],
    hints: ['Comece i em 1 e use i <= n.', 'Dentro do for, faça total += i.', 'Depois da chave do laço, mostre total.'],
    commonMistake: 'i < n deixa o último número de fora. Não esquecer i++ evita uma repetição que nunca termina.',
    solutionCode: cpp('    int n;\n    cin >> n;\n    long long total = 0;\n    for (int i = 1; i <= n; i++) {\n        total += i;\n    }\n    cout << total << "\\n";'),
    transfer: { prompt: 'Leia n entre 0 e 1000 e some apenas os pares de 1 até n. i % 2 == 0 identifica um número par.', starterCode: cpp('    int n;\n    cin >> n;\n    long long total = 0;\n    // Combine laço e condição.'), cases: [test('Até seis', '6\n', '12\n'), test('Fim ímpar', '5\n', '6\n'), test('Sem pares', '1\n', '0\n'), test('Faixa vazia', '0\n', '0\n')], solutionCode: cpp('    int n;\n    cin >> n;\n    long long total = 0;\n    for (int i = 1; i <= n; i++) {\n        if (i % 2 == 0) {\n            total += i;\n        }\n    }\n    cout << total << "\\n";') },
  }),
  lesson('cpp', 6, {
    id: 'vetores', title: 'Guarde dados em um vector', summary: 'Construa uma coleção e percorra seus valores.',
    concepts: ['vector', 'push_back', 'for por intervalo', 'coleção vazia'],
    learn: [
      '#include <vector> permite criar vector<int> quantidades. push_back(valor) acrescenta um elemento ao final.',
      'Depois de ler n valores, for (int valor : quantidades) percorre os elementos sem precisar controlar índices.',
      'Um vector pode ficar vazio. O laço por intervalo não executa nesse caso, por isso um acumulador iniciado em zero continua correto.',
    ],
    prediction: predict(cpp('    vector<int> valores = {2, 5};\n    valores.push_back(3);\n    int total = 0;\n    for (int valor : valores) total += valor;\n    cout << valores.size() << "\\n" << total << "\\n";', { headers: ['vector'] }), ['2\n7', '3\n10', '3\n253'], 1, 'Há três elementos depois de push_back. Eles somam 10.'),
    task: 'Leia n entre 0 e 100 e depois n quantidades inteiras entre 0 e 1000000. Guarde-as em um vector e mostre a soma. Use long long para o total.',
    starterCode: cpp('    int n;\n    cin >> n;\n    vector<int> quantidades;\n    // Leia n valores e guarde-os com push_back.\n    // Percorra a coleção para somar.', { headers: ['vector'] }),
    cases: [test('Três caixas', '3\n2\n5\n3\n', '10\n'), test('Coleção vazia', '0\n', '0\n'), test('Um zero', '1\n0\n', '0\n'), test('Valores repetidos', '4\n10\n10\n10\n10\n', '40\n')],
    hints: ['Um laço de i = 0 até i < n lê todos os valores.', 'Leia em uma variável int valor e faça quantidades.push_back(valor).', 'Um segundo laço por intervalo pode fazer total += valor.'],
    commonMistake: 'Um vector vazio não tem posição zero. push_back cria elementos; escrever quantidades[0] antes de adicioná-los é inválido.',
    solutionCode: cpp('    int n;\n    cin >> n;\n    vector<int> quantidades;\n    for (int i = 0; i < n; i++) {\n        int valor;\n        cin >> valor;\n        quantidades.push_back(valor);\n    }\n    long long total = 0;\n    for (int valor : quantidades) total += valor;\n    cout << total << "\\n";', { headers: ['vector'] }),
    transfer: { prompt: 'Leia n e n inteiros. Conte quantos são estritamente positivos. Zero e negativos não contam.', starterCode: cpp('    int n;\n    cin >> n;\n    vector<int> valores;\n    // Leia a coleção e conte os positivos.', { headers: ['vector'] }), cases: [test('Sinais misturados', '5\n2\n0\n-3\n4\n1\n', '3\n'), test('Coleção vazia', '0\n', '0\n'), test('Sem positivos', '3\n0\n-1\n-2\n', '0\n')], solutionCode: cpp('    int n;\n    cin >> n;\n    vector<int> valores;\n    for (int i = 0; i < n; i++) {\n        int valor;\n        cin >> valor;\n        valores.push_back(valor);\n    }\n    int positivos = 0;\n    for (int valor : valores) {\n        if (valor > 0) positivos++;\n    }\n    cout << positivos << "\\n";', { headers: ['vector'] }) },
  }),
  lesson('cpp', 7, {
    id: 'funcoes', title: 'Separe uma tarefa em função', summary: 'Reutilize um cálculo com parâmetros e retorno.',
    concepts: ['função', 'parâmetro', 'return', 'tipo do retorno'],
    learn: [
      'int dobro(int valor) define uma função que recebe um inteiro e devolve outro. Coloque-a antes de main para que a chamada seja conhecida.',
      'return valor * 2; entrega o resultado à parte do programa que chamou a função. A função pode receber números diferentes em cada chamada.',
      'Deixe a função calcular e main cuidar da entrada e da saída. Isso permite reaproveitar o cálculo sem imprimir mensagens extras.',
    ],
    prediction: predict(cpp('    cout << dobro(3) + dobro(4) << "\\n";', { before: 'int dobro(int valor) {\n    return valor * 2;\n}' }), ['7', '14', '6\n8'], 1, 'As chamadas devolvem 6 e 8. cout mostra a soma 14.'),
    task: 'Crie dobro(int valor). Leia dois inteiros entre -1000000 e 1000000. Mostre o dobro de cada um em uma linha.',
    starterCode: cpp('    int a, b;\n    cin >> a >> b;\n    // Chame dobro para cada valor.', { before: 'int dobro(int valor) {\n    // Substitua o retorno pelo cálculo.\n    return 0;\n}' }),
    cases: [test('Dois positivos', '3\n4\n', '6\n8\n'), test('Zero e negativo', '0\n-7\n', '0\n-14\n'), test('Dois iguais', '5\n5\n', '10\n10\n')],
    hints: ['Na função, use return valor * 2;.', 'Chame dobro(a) e dobro(b).', 'Envie cada retorno ao cout com "\\n" entre os resultados.'],
    commonMistake: 'Uma função int precisa devolver um inteiro. return em main não substitui o retorno da função dobro.',
    solutionCode: cpp('    int a, b;\n    cin >> a >> b;\n    cout << dobro(a) << "\\n" << dobro(b) << "\\n";', { before: 'int dobro(int valor) {\n    return valor * 2;\n}' }),
    transfer: { prompt: 'Crie long long area(long long base, long long altura). Leia base e altura não negativas até 1000000 e mostre a área do retângulo.', starterCode: cpp('    long long base, altura;\n    cin >> base >> altura;\n    // Mostre o resultado da função.', { before: 'long long area(long long base, long long altura) {\n    return 0;\n}' }), cases: [test('Retângulo', '8\n3\n', '24\n'), test('Altura zero', '12\n0\n', '0\n'), test('Área grande', '1000000\n1000000\n', '1000000000000\n')], solutionCode: cpp('    long long base, altura;\n    cin >> base >> altura;\n    cout << area(base, altura) << "\\n";', { before: 'long long area(long long base, long long altura) {\n    return base * altura;\n}' }) },
  }),
  lesson('cpp', 8, {
    id: 'estufa', title: 'Projeto 2 · Guardião da estufa', kind: 'project', duration: 30, summary: 'Combine função, vector e decisão para acompanhar sensores.',
    concepts: ['const', 'referência', 'vector', 'contagem'],
    learn: [
      'Leia n temperaturas em um vector. Temperaturas estritamente acima de 30 geram alerta; 30 é um valor permitido.',
      'int contar_alertas(const vector<int>& leituras) recebe a coleção sem fazer uma cópia. const indica que a função não a modifica; & passa uma referência.',
      'A função devolve uma contagem. main decide entre OK e ALERTA quantidade. A ausência de leituras deve produzir OK.',
    ],
    prediction: predict(cpp('    vector<int> leituras = {30, 31, 29};\n    int alertas = 0;\n    for (int valor : leituras) {\n        if (valor > 30) alertas++;\n    }\n    cout << alertas << "\\n";', { headers: ['vector'] }), ['1', '2', '3'], 0, 'Somente 31 é estritamente maior que 30.'),
    task: 'Leia n entre 0 e 100 e n temperaturas inteiras. Use contar_alertas para contar valores > 30. Mostre ALERTA contagem se houver algum; senão, OK.',
    starterCode: cpp('    int n;\n    cin >> n;\n    vector<int> leituras;\n    // Leia as temperaturas e use a função.', { headers: ['vector'], before: 'int contar_alertas(const vector<int>& leituras) {\n    // Percorra as leituras e conte.\n    return 0;\n}' }),
    cases: [test('Temperaturas permitidas', '3\n20\n30\n29\n', 'OK\n'), test('Dois alertas', '4\n31\n30\n45\n10\n', 'ALERTA 2\n'), test('Sem leituras', '0\n', 'OK\n'), test('Uma no limite', '1\n30\n', 'OK\n'), test('Uma acima', '1\n31\n', 'ALERTA 1\n')],
    hints: ['A função começa com int total = 0; e percorre leituras.', 'Use if (valor > 30) total++; e devolva total após o laço.', 'Chame a função depois de ler os dados e escolha a mensagem pelo resultado.'],
    commonMistake: 'Devolver dentro do laço interrompe a contagem. >= 30 também muda a regra do sensor.',
    solutionCode: cpp('    int n;\n    cin >> n;\n    vector<int> leituras;\n    for (int i = 0; i < n; i++) {\n        int valor;\n        cin >> valor;\n        leituras.push_back(valor);\n    }\n    int alertas = contar_alertas(leituras);\n    if (alertas > 0) cout << "ALERTA " << alertas << "\\n";\n    else cout << "OK\\n";', { headers: ['vector'], before: 'int contar_alertas(const vector<int>& leituras) {\n    int total = 0;\n    for (int valor : leituras) {\n        if (valor > 30) total++;\n    }\n    return total;\n}' }),
    transfer: { title: 'Variação · Estoque baixo', prompt: 'Leia n e n quantidades não negativas. Conte valores menores que 5. Se houver algum, mostre REPOR contagem; senão, ESTOQUE OK.', starterCode: cpp('    int n;\n    cin >> n;\n    // Leia a coleção, conte e escolha a mensagem.', { headers: ['vector'], before: 'int contar_baixos(const vector<int>& quantidades) {\n    return 0;\n}' }), cases: [test('Duas reposições', '4\n4\n5\n0\n8\n', 'REPOR 2\n'), test('No limite', '2\n5\n10\n', 'ESTOQUE OK\n'), test('Sem produtos', '0\n', 'ESTOQUE OK\n')], solutionCode: cpp('    int n;\n    cin >> n;\n    vector<int> quantidades;\n    for (int i = 0; i < n; i++) {\n        int valor;\n        cin >> valor;\n        quantidades.push_back(valor);\n    }\n    int baixos = contar_baixos(quantidades);\n    if (baixos > 0) cout << "REPOR " << baixos << "\\n";\n    else cout << "ESTOQUE OK\\n";', { headers: ['vector'], before: 'int contar_baixos(const vector<int>& quantidades) {\n    int total = 0;\n    for (int valor : quantidades) {\n        if (valor < 5) total++;\n    }\n    return total;\n}' }) },
  }),
  lesson('cpp', 9, {
    id: 'textos', title: 'Percorra uma linha de texto', summary: 'Trate texto como uma coleção de caracteres.',
    concepts: ['char', 'string', 'getline', 'caractere de espaço'],
    learn: [
      'Uma string pode ser percorrida: for (char letra : texto). char representa um caractere; use aspas simples para comparar, como letra == \' \'.',
      'getline lê a linha inteira, incluindo espaços no início, no meio e no fim. Uma linha vazia tem zero caracteres.',
      'Vamos contar o caractere espaço, não palavras. "A  B" tem dois espaços, mesmo que eles estejam lado a lado. Tabulações não fazem parte das entradas deste desafio.',
    ],
    prediction: predict(cpp('    string texto = "A  B";\n    int espacos = 0;\n    for (char letra : texto) {\n        if (letra == \' \') espacos++;\n    }\n    cout << espacos << "\\n";', { headers: ['string'] }), ['1', '2', '4'], 1, 'Entre A e B há dois caracteres de espaço; o laço conta ambos.'),
    task: 'Leia uma linha de texto de até 200 caracteres e mostre quantos espaços ela contém. Conte também os espaços nas pontas. A linha pode estar vazia.',
    starterCode: cpp('    string texto;\n    getline(cin, texto);\n    int espacos = 0;\n    // Percorra e conte o caractere espaço.', { headers: ['string'] }),
    cases: [test('Frase curta', 'ola mundo\n', '1\n'), test('Espaços repetidos', 'A  B\n', '2\n'), test('Espaços nas pontas', ' oi \n', '2\n'), test('Sem espaços', 'Python\n', '0\n'), test('Linha vazia', '\n', '0\n')],
    hints: ['Use for (char letra : texto).', 'Compare letra com \' \' usando ==.', 'Aumente espacos para cada ocorrência e mostre a contagem depois do laço.'],
    commonMistake: '" " é uma string; \' \' é um caractere. cin >> texto perderia parte da linha depois do primeiro espaço.',
    solutionCode: cpp('    string texto;\n    getline(cin, texto);\n    int espacos = 0;\n    for (char letra : texto) {\n        if (letra == \' \') espacos++;\n    }\n    cout << espacos << "\\n";', { headers: ['string'] }),
    transfer: { prompt: 'Leia uma linha e conte os pontos de exclamação (!). A linha pode estar vazia; outros sinais não contam.', starterCode: cpp('    string texto;\n    getline(cin, texto);\n    // Conte apenas !.', { headers: ['string'] }), cases: [test('Três exclamações', 'Oi!!!\n', '3\n'), test('Outros sinais', 'Oi? Tudo bem.\n', '0\n'), test('Sinais separados', '! oi !\n', '2\n'), test('Vazio', '\n', '0\n')], solutionCode: cpp('    string texto;\n    getline(cin, texto);\n    int quantidade = 0;\n    for (char letra : texto) {\n        if (letra == \'!\') quantidade++;\n    }\n    cout << quantidade << "\\n";', { headers: ['string'] }) },
  }),
  lesson('cpp', 10, {
    id: 'busca', title: 'Busque sem sair da coleção', summary: 'Encontre a primeira posição de um valor e cuide do caso ausente.',
    concepts: ['índice', 'vector', 'busca linear', 'break', 'sentinela'],
    learn: [
      'Os índices começam em zero. Uma coleção com n elementos tem posições válidas de 0 até n - 1.',
      'Inicialize posicao = -1 para representar que o valor ainda não foi encontrado. Percorra de i = 0 enquanto i < n.',
      'Quando valores[i] for igual ao alvo, guarde i e use break para parar. Isso preserva a primeira ocorrência. Com n = 0, não há acesso a nenhuma posição.',
    ],
    prediction: predict(cpp('    vector<int> valores = {4, 7, 7};\n    int posicao = -1;\n    for (int i = 0; i < 3; i++) {\n        if (valores[i] == 7) {\n            posicao = i;\n            break;\n        }\n    }\n    cout << posicao << "\\n";', { headers: ['vector'] }), ['0', '1', '2'], 1, 'O primeiro 7 está no índice 1. break impede substituir a resposta pela ocorrência do índice 2.'),
    task: 'Leia n entre 0 e 100, n inteiros e um alvo. Mostre o índice da primeira ocorrência do alvo, começando em zero, ou -1 se ele não existir.',
    starterCode: cpp('    int n;\n    cin >> n;\n    vector<int> valores(n);\n    for (int i = 0; i < n; i++) cin >> valores[i];\n    int alvo;\n    cin >> alvo;\n    int posicao = -1;\n    // Encontre a primeira ocorrência.', { headers: ['vector'] }),
    cases: [test('Primeira ocorrência repetida', '3\n4\n7\n7\n7\n', '1\n'), test('Na primeira posição', '2\n9\n1\n9\n', '0\n'), test('Na última posição', '3\n1\n2\n3\n3\n', '2\n'), test('Valor ausente', '2\n4\n5\n6\n', '-1\n'), test('Coleção vazia', '0\n9\n', '-1\n')],
    hints: ['Compare cada valores[i] com alvo.', 'Ao encontrar, guarde i em posicao e use break.', 'Mostre posicao mesmo se continuar sendo -1.'],
    commonMistake: 'i <= n acessa uma posição que não existe. Sem break, valores repetidos podem trocar a primeira ocorrência pela última.',
    solutionCode: cpp('    int n;\n    cin >> n;\n    vector<int> valores(n);\n    for (int i = 0; i < n; i++) cin >> valores[i];\n    int alvo;\n    cin >> alvo;\n    int posicao = -1;\n    for (int i = 0; i < n; i++) {\n        if (valores[i] == alvo) {\n            posicao = i;\n            break;\n        }\n    }\n    cout << posicao << "\\n";', { headers: ['vector'] }),
    transfer: { prompt: 'Use o mesmo formato de entrada, mas mostre a quantidade de ocorrências do alvo. Se não houver nenhuma, mostre zero.', starterCode: cpp('    int n;\n    cin >> n;\n    vector<int> valores(n);\n    for (int i = 0; i < n; i++) cin >> valores[i];\n    int alvo;\n    cin >> alvo;\n    // Conte todas as ocorrências.', { headers: ['vector'] }), cases: [test('Duas ocorrências', '3\n4\n7\n7\n7\n', '2\n'), test('Nenhuma', '2\n4\n5\n6\n', '0\n'), test('Coleção vazia', '0\n9\n', '0\n'), test('Todas iguais', '3\n0\n0\n0\n0\n', '3\n')], solutionCode: cpp('    int n;\n    cin >> n;\n    vector<int> valores(n);\n    for (int i = 0; i < n; i++) cin >> valores[i];\n    int alvo;\n    cin >> alvo;\n    int quantidade = 0;\n    for (int valor : valores) {\n        if (valor == alvo) quantidade++;\n    }\n    cout << quantidade << "\\n";', { headers: ['vector'] }) },
  }),
  lesson('cpp', 11, {
    id: 'depuracao', title: 'Corrija com evidências', summary: 'Encontre dois defeitos em um programa que compila.',
    concepts: ['depuração', 'acumulador', 'caso mínimo', 'limite inclusivo'],
    learn: [
      'Compilar sem erro não prova que a solução está correta. Uma entrada pequena ajuda a acompanhar o valor de cada variável.',
      'O código inicial tenta somar de 1 até n, mas começa total com um valor errado e usa um limite que exclui n.',
      'Teste n = 0 para investigar a inicialização e n = 3 para investigar a última parcela. Depois valide todos os cenários para evitar uma correção que funcione só no exemplo.',
    ],
    prediction: predict(cpp('    int total = 1;\n    for (int i = 1; i < 3; i++) total += i;\n    cout << total << "\\n";'), ['3', '4', '6'], 1, 'O programa começa em 1 e soma 1 e 2. Ele mostra 4, embora o objetivo fosse somar até 3.'),
    task: 'Corrija os dois defeitos para ler n entre 0 e 1000 e mostrar a soma de 1 até n, incluindo n. Não troque o programa por uma resposta fixa.',
    starterCode: cpp('    int n;\n    cin >> n;\n    long long total = 1;\n    for (int i = 1; i < n; i++) {\n        total += i;\n    }\n    cout << total << "\\n";'),
    cases: [test('Expõe os defeitos', '3\n', '6\n'), test('Intervalo vazio', '0\n', '0\n'), test('Uma parcela', '1\n', '1\n'), test('Mais parcelas', '10\n', '55\n')],
    hints: ['A soma sem parcelas começa em zero.', 'O último valor precisa entrar: a condição é i <= n.', 'Corrija total = 0 e i <= n e rode todos os testes.'],
    commonMistake: 'Corrigir somente a condição ainda deixa um erro de uma unidade. Duas falhas podem coincidir e esconder diferenças em algumas entradas.',
    solutionCode: cpp('    int n;\n    cin >> n;\n    long long total = 0;\n    for (int i = 1; i <= n; i++) total += i;\n    cout << total << "\\n";'),
    transfer: { prompt: 'Repare o contador de múltiplos de 3. Ele deve contar os números de 1 até n, inclusive, divisíveis por 3. n está entre 0 e 1000.', starterCode: cpp('    int n;\n    cin >> n;\n    int quantidade = 1;\n    for (int i = 1; i < n; i++) {\n        if (i % 3 == 0) quantidade++;\n    }\n    cout << quantidade << "\\n";'), cases: [test('Inclui o limite', '6\n', '2\n'), test('Sem múltiplos', '2\n', '0\n'), test('Intervalo vazio', '0\n', '0\n'), test('Limite não múltiplo', '10\n', '3\n')], solutionCode: cpp('    int n;\n    cin >> n;\n    int quantidade = 0;\n    for (int i = 1; i <= n; i++) {\n        if (i % 3 == 0) quantidade++;\n    }\n    cout << quantidade << "\\n";') },
  }),
  lesson('cpp', 12, {
    id: 'placar', title: 'Projeto 3 · Placar da equipe', kind: 'project', duration: 40, summary: 'Crie um relatório com total, melhor resultado e meta atingida.',
    concepts: ['decomposição', 'vector', 'funções', 'máximo', 'relatório'],
    learn: [
      'Leia n resultados inteiros não negativos e uma meta. Organize os resultados em vector<int>; n pode ser zero, e cada resultado e a meta estão entre 0 e 1000000.',
      'Crie total_pontos para somar a coleção e melhor_resultado para encontrar o maior valor. Com coleção vazia, ambas devolvem zero.',
      'O relatório tem três linhas: TOTAL valor, MELHOR valor e META OK ou META PENDENTE. A meta é atingida quando total >= meta. Zero pontos atinge uma meta zero.',
    ],
    prediction: predict(cpp('    vector<int> pontos = {4, 9, 2};\n    int melhor = 0;\n    for (int valor : pontos) {\n        if (valor > melhor) melhor = valor;\n    }\n    cout << melhor << "\\n";', { headers: ['vector'] }), ['2', '9', '15'], 1, 'melhor guarda o maior valor visto: começa em zero, passa a 4, depois 9 e permanece 9.'),
    task: 'Leia n entre 0 e 100, n resultados e a meta. Calcule total e maior resultado com funções. Mostre TOTAL valor, MELHOR valor e META OK se total >= meta, ou META PENDENTE em caso contrário.',
    starterCode: cpp('    int n;\n    cin >> n;\n    vector<int> pontos;\n    // Leia os resultados e a meta; produza o relatório.', { headers: ['vector'], before: 'long long total_pontos(const vector<int>& pontos) {\n    return 0;\n}\n\nint melhor_resultado(const vector<int>& pontos) {\n    return 0;\n}' }),
    cases: [test('Meta superada', '3\n4\n9\n2\n10\n', 'TOTAL 15\nMELHOR 9\nMETA OK\n'), test('Meta exata', '2\n3\n7\n10\n', 'TOTAL 10\nMELHOR 7\nMETA OK\n'), test('Meta pendente', '2\n3\n4\n10\n', 'TOTAL 7\nMELHOR 4\nMETA PENDENTE\n'), test('Equipe sem resultados, meta zero', '0\n0\n', 'TOTAL 0\nMELHOR 0\nMETA OK\n'), test('Equipe sem resultados, meta positiva', '0\n1\n', 'TOTAL 0\nMELHOR 0\nMETA PENDENTE\n'), test('Melhor resultado repetido', '3\n8\n8\n0\n16\n', 'TOTAL 16\nMELHOR 8\nMETA OK\n')],
    hints: ['total_pontos acumula em long long e melhor_resultado começa com melhor = 0.', 'Depois de ler n resultados, leia a meta em uma nova variável.', 'A condição usa total >= meta. Produza as três linhas na ordem pedida.'],
    commonMistake: 'Não inicialize o maior com pontos[0], pois a coleção pode estar vazia. Usar > na meta rejeita o caso exato.',
    solutionCode: cpp('    int n;\n    cin >> n;\n    vector<int> pontos;\n    for (int i = 0; i < n; i++) {\n        int valor;\n        cin >> valor;\n        pontos.push_back(valor);\n    }\n    long long meta;\n    cin >> meta;\n    long long total = total_pontos(pontos);\n    int melhor = melhor_resultado(pontos);\n    cout << "TOTAL " << total << "\\n";\n    cout << "MELHOR " << melhor << "\\n";\n    if (total >= meta) cout << "META OK\\n";\n    else cout << "META PENDENTE\\n";', { headers: ['vector'], before: 'long long total_pontos(const vector<int>& pontos) {\n    long long total = 0;\n    for (int valor : pontos) total += valor;\n    return total;\n}\n\nint melhor_resultado(const vector<int>& pontos) {\n    int melhor = 0;\n    for (int valor : pontos) {\n        if (valor > melhor) melhor = valor;\n    }\n    return melhor;\n}' }),
    transfer: { title: 'Variação · Resultados acima do limite', prompt: 'Leia n, n resultados e um limite. Conte resultados estritamente maiores que o limite e some somente esses resultados. Mostre ACIMA contagem e SOMA valor em duas linhas. Igualdade não entra.', starterCode: cpp('    int n;\n    cin >> n;\n    vector<int> pontos;\n    // Leia os dados e produza o relatório filtrado.', { headers: ['vector'] }), cases: [test('Filtra dois resultados', '4\n4\n9\n2\n7\n5\n', 'ACIMA 2\nSOMA 16\n'), test('Igual não entra', '2\n5\n5\n5\n', 'ACIMA 0\nSOMA 0\n'), test('Coleção vazia', '0\n0\n', 'ACIMA 0\nSOMA 0\n'), test('Limite zero', '3\n0\n1\n2\n0\n', 'ACIMA 2\nSOMA 3\n')], solutionCode: cpp('    int n;\n    cin >> n;\n    vector<int> pontos;\n    for (int i = 0; i < n; i++) {\n        int valor;\n        cin >> valor;\n        pontos.push_back(valor);\n    }\n    int limite;\n    cin >> limite;\n    int quantidade = 0;\n    long long soma = 0;\n    for (int valor : pontos) {\n        if (valor > limite) {\n            quantidade++;\n            soma += valor;\n        }\n    }\n    cout << "ACIMA " << quantidade << "\\n";\n    cout << "SOMA " << soma << "\\n";', { headers: ['vector'] }) },
  }),
];

export const LEARNING_TRACKS = {
  python: {
    id: 'python', title: 'Python · Da primeira linha ao projeto', shortTitle: 'Python', icon: 'data_object',
    description: 'Aprenda a conversar com o usuário, tomar decisões, organizar dados e construir um orçamento funcional.',
    level: 'Comece do zero', language: 'python', extension: 'py', lessons: pythonLessons,
    projects: ['cantina', 'estufa', 'loja'], estimatedMinutes: pythonLessons.reduce((total, item) => total + item.duration, 0),
    outcomes: ['Ler e transformar entradas', 'Combinar decisões e repetições', 'Organizar listas e dicionários', 'Dividir soluções em funções', 'Investigar erros com casos de limite'],
  },
  cpp: {
    id: 'cpp', title: 'C++ · Construa e teste suas ideias', shortTitle: 'C++', icon: 'terminal',
    description: 'Aprenda tipos, compilação, coleções e funções; crie programas que tomam decisões e produzem relatórios.',
    level: 'Comece do zero', language: 'cpp', extension: 'cpp', lessons: cppLessons,
    projects: ['cantina', 'estufa', 'placar'], estimatedMinutes: cppLessons.reduce((total, item) => total + item.duration, 0),
    outcomes: ['Compilar e ler diagnósticos', 'Escolher tipos e ler entradas', 'Controlar laços e limites', 'Organizar vectors e funções', 'Validar programas com entradas distintas'],
  },
};

export function getLesson(language, id) {
  return LEARNING_TRACKS[language]?.lessons.find(item => item.id === id) || null;
}

export function getTrack(language) {
  return LEARNING_TRACKS[language] || null;
}
