window.OMINI_TEACHER_CONFIGS = {
  matematica: {
    type: "matematica",
    short: "Matemática",
    title: "Professor de Matemática",
    icon: "calculate",
    labIcon: "function",
    labLabel: "Laboratório matemático",
    labSingular: "laboratório matemático",
    kicker: "Central matemática",
    hero: "Transforme dificuldades em percursos de descoberta.",
    description:
      "Organize investigações, simuladores e avaliações por habilidade com dados reais das turmas vinculadas.",
    boardKicker: "Aprendizagem por evidências",
    boardTitle: "Laboratórios e investigações",
    labCreateTitle: "Monte uma investigação matemática",
    labTitlePlaceholder: "Ex.: Explorando funções quadráticas",
    configLabel: "Habilidade ou descritor",
    configPlaceholder: "Ex.: EM13MAT302",
    configKey: "habilidade",
    evaluationTitle: "Prepare uma avaliação por habilidades",
    evaluationPlaceholder: "Ex.: Diagnóstico de funções e geometria",
    evaluationModel: "habilidades_matematicas",
    questionPlaceholder:
      "Apresente um problema, dados e o que deve ser calculado.",
    labFormats: [
      { value: "graficos", label: "Gráficos interativos" },
      { value: "formulas", label: "Editor de fórmulas" },
      { value: "simulacao", label: "Simulação matemática" },
      { value: "resolucao_problemas", label: "Resolução de problemas" },
    ],
    questionTypes: [
      { value: "calculo", label: "Cálculo" },
      { value: "multipla_escolha", label: "Múltipla escolha" },
      { value: "verdadeiro_falso", label: "Verdadeiro ou falso" },
      { value: "dissertativa", label: "Demonstração" },
    ],
    mathTemplates: [
      {
        value: "livre",
        label: "Questão livre",
        icon: "edit_square",
        description: "Monte cálculo, alternativa ou demonstração do zero.",
        descriptors: "Qualquer descritor",
        questionType: "calculo",
      },
      {
        value: "plano_cartesiano",
        label: "Plano cartesiano",
        icon: "grid_4x4",
        description: "O aluno marca um ponto diretamente no plano.",
        descriptors: "D043_M",
        questionType: "resposta_curta",
      },
      {
        value: "reta_numerica",
        label: "Reta numérica",
        icon: "linear_scale",
        description: "O aluno posiciona um valor em uma reta graduada.",
        descriptors: "D009_M · D033_M",
        questionType: "numerica",
      },
      {
        value: "pitagoras",
        label: "Triângulo e medidas",
        icon: "change_history",
        description: "Represente catetos, hipotenusa e unidades.",
        descriptors: "D049_M",
        questionType: "numerica",
      },
      {
        value: "geometria_medidas",
        label: "Laboratório de medidas",
        icon: "deployed_code",
        description: "Crie figuras 2D e sólidos 3D com medidas manipuláveis.",
        descriptors: "Geometria plana e espacial",
        questionType: "numerica",
      },
      {
        value: "grafico_barras",
        label: "Leitura de gráfico",
        icon: "bar_chart",
        description: "Transforme uma tabela curta em gráfico clicável.",
        descriptors: "D064_M",
        questionType: "unica_escolha",
      },
    ],
    pages: {
      dashboard: {
        title: "Visão matemática",
        subtitle: "Habilidades, turmas e intervenções em um só lugar.",
      },
      laboratorio: {
        title: "Laboratório matemático",
        subtitle: "Crie explorações que tornam conceitos abstratos visíveis.",
      },
      avaliacoes: {
        title: "Avaliações de Matemática",
        subtitle:
          "Combine cálculo, raciocínio e demonstração com critérios claros.",
      },
    },
  },
  portugues: {
    type: "portugues",
    short: "Português",
    title: "Professor de Português",
    icon: "edit_note",
    labIcon: "menu_book",
    labLabel: "Oficina de linguagem",
    labSingular: "oficina de linguagem",
    kicker: "Central de linguagens",
    hero: "Acompanhe leitura, autoria e argumentação com propósito.",
    description:
      "Crie oficinas de leitura e escrita, prepare avaliações e acompanhe redações das turmas vinculadas.",
    boardKicker: "Produção e leitura",
    boardTitle: "Oficinas em andamento",
    labCreateTitle: "Crie uma oficina de linguagem",
    labTitlePlaceholder: "Ex.: Vozes da crônica brasileira",
    configLabel: "Gênero ou competência",
    configPlaceholder: "Ex.: argumentação e repertório",
    configKey: "competencia",
    evaluationTitle: "Prepare uma avaliação de linguagem",
    evaluationPlaceholder: "Ex.: Leitura crítica e recursos expressivos",
    evaluationModel: "linguagens_e_competencias",
    questionPlaceholder:
      "Inclua o trecho ou contexto e formule uma pergunta interpretativa.",
    labFormats: [
      { value: "leitura_orientada", label: "Leitura orientada" },
      { value: "producao_textual", label: "Produção textual" },
      { value: "debate", label: "Debate argumentativo" },
      { value: "oficina_linguagem", label: "Oficina de linguagem" },
    ],
    questionTypes: [
      { value: "multipla_escolha", label: "Múltipla escolha" },
      { value: "dissertativa", label: "Resposta interpretativa" },
      { value: "verdadeiro_falso", label: "Verdadeiro ou falso" },
      { value: "estudo_caso", label: "Análise de texto" },
    ],
    pages: {
      dashboard: {
        title: "Visão de Linguagens",
        subtitle: "Leitura, escrita, oficinas e devolutivas conectadas.",
      },
      laboratorio: {
        title: "Oficina de linguagem",
        subtitle: "Prepare experiências de leitura, autoria e debate.",
      },
      avaliacoes: {
        title: "Avaliações de Português",
        subtitle: "Construa questões interpretativas e critérios de correção.",
      },
      redacoes: {
        title: "Redações",
        subtitle:
          "Corrija textos, registre devolutivas e acompanhe a evolução real.",
      },
    },
  },
  tecnico_administracao: {
    type: "tecnico_administracao",
    short: "Administração",
    title: "Professor Técnico em Administração",
    icon: "business_center",
    labIcon: "account_tree",
    labLabel: "Estúdio de projetos",
    labSingular: "projeto de gestão",
    kicker: "Central de gestão",
    hero: "Leve situações profissionais reais para dentro da turma.",
    description:
      "Planeje estudos de caso, simulações empresariais e avaliações por competência profissional.",
    boardKicker: "Fluxo de projetos",
    boardTitle: "Pipeline das turmas",
    labCreateTitle: "Estruture um projeto de gestão",
    labTitlePlaceholder: "Ex.: Plano de negócio da comunidade",
    configLabel: "Competência profissional",
    configPlaceholder: "Ex.: planejamento financeiro",
    configKey: "competencia_profissional",
    evaluationTitle: "Prepare uma avaliação aplicada",
    evaluationPlaceholder: "Ex.: Estudo de caso de fluxo de caixa",
    evaluationModel: "competencias_profissionais_administracao",
    questionPlaceholder:
      "Descreva o cenário empresarial, os dados e a decisão esperada.",
    labFormats: [
      { value: "estudo_caso", label: "Estudo de caso" },
      { value: "projeto_equipe", label: "Projeto em equipe" },
      { value: "simulacao_empresarial", label: "Simulação empresarial" },
      { value: "plano_financeiro", label: "Plano financeiro" },
    ],
    questionTypes: [
      { value: "estudo_caso", label: "Estudo de caso" },
      { value: "dissertativa", label: "Decisão justificada" },
      { value: "multipla_escolha", label: "Múltipla escolha" },
      { value: "calculo", label: "Cálculo financeiro" },
    ],
    pages: {
      dashboard: {
        title: "Visão de Administração",
        subtitle: "Projetos, equipes e competências profissionais em fluxo.",
      },
      laboratorio: {
        title: "Estúdio de projetos",
        subtitle: "Organize situações reais, papéis, etapas e entregáveis.",
      },
      avaliacoes: {
        title: "Avaliações de Administração",
        subtitle: "Avalie decisões, processos e aplicação prática.",
      },
    },
  },
  tecnico_informatica: {
    type: "tecnico_informatica",
    short: "Informática",
    title: "Professor Técnico em Informática",
    icon: "terminal",
    labIcon: "code",
    labLabel: "Laboratórios técnicos",
    labSingular: "laboratório técnico",
    kicker: "Central técnica",
    hero: "Conecte código, infraestrutura e evidências de aprendizagem.",
    description:
      "Crie laboratórios de programação, redes e dados com entregas rastreáveis e avaliações técnicas.",
    boardKicker: "Operação dos laboratórios",
    boardTitle: "Ambientes e entregas",
    labCreateTitle: "Configure um laboratório técnico",
    labTitlePlaceholder: "Ex.: API REST com autenticação",
    configLabel: "Stack ou ambiente",
    configPlaceholder: "Ex.: JavaScript, Node.js e PostgreSQL",
    configKey: "stack",
    evaluationTitle: "Prepare uma avaliação técnica",
    evaluationPlaceholder: "Ex.: Programação web e banco de dados",
    evaluationModel: "competencias_tecnicas_informatica",
    questionPlaceholder:
      "Descreva o requisito, entradas, saídas e critérios técnicos.",
    labFormats: [
      { value: "desafio_codigo", label: "Desafio de código" },
      { value: "laboratorio_redes", label: "Laboratório de redes" },
      { value: "banco_dados", label: "Banco de dados" },
      { value: "revisao_codigo", label: "Revisão de código" },
    ],
    questionTypes: [
      { value: "codigo", label: "Código" },
      { value: "estudo_caso", label: "Cenário técnico" },
      { value: "multipla_escolha", label: "Múltipla escolha" },
      { value: "verdadeiro_falso", label: "Verdadeiro ou falso" },
    ],
    pages: {
      dashboard: {
        title: "Visão de Informática",
        subtitle: "Laboratórios, entregas e evolução técnica em tempo real.",
      },
      laboratorio: {
        title: "Laboratórios técnicos",
        subtitle: "Configure ambientes, desafios e evidências de entrega.",
      },
      avaliacoes: {
        title: "Avaliações de Informática",
        subtitle: "Combine código, arquitetura e resolução de problemas.",
      },
    },
  },
};
